miembros:
    pattern:  /
    defaults: { _controller: FrontendBundle:Miembro:index }

coro:
    pattern:  /coro
    defaults: { _controller: FrontendBundle:Miembro:coro }

orquesta:
    pattern:  /orquesta
    defaults: { _controller: FrontendBundle:Miembro:orquesta }

direccion:
    pattern:  /direccion
    defaults: { _controller: FrontendBundle:Miembro:direccion }

juntaDirectiva:
    pattern:  /junta-directiva
    defaults: { _controller: FrontendBundle:Miembro:junta }

ficha_maria_montes:
    pattern:  /maria-montes
    defaults: { _controller: FrontendBundle:Miembro:mariaMontes }
    
ficha_elena_roldan:
    pattern:  /elena-roldan
    defaults: { _controller: FrontendBundle:Miembro:elenaRoldan }

ficha_txaber_fernandez:
    pattern:  /txaber-fernandez
    defaults: { _controller: FrontendBundle:Miembro:txaberFernandez }