miembros:
    pattern:  /
    defaults: { _controller: FrontendBundle:Miembros:index }

coro:
    pattern:  /coro
    defaults: { _controller: FrontendBundle:Miembros:coro }

orquesta:
    pattern:  /orquesta
    defaults: { _controller: FrontendBundle:Miembros:orquesta }

direccion:
    pattern:  /direccion
    defaults: { _controller: FrontendBundle:Miembros:direccion }

juntaDirectiva:
    pattern:  /junta-directiva
    defaults: { _controller: FrontendBundle:Miembros:junta }


ficha_paula:
    pattern:  /paula-perez
    defaults: { _controller: FrontendBundle:Miembros:direccionPaula }