homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:General:index }

historia:
    pattern:  /historia
    defaults: { _controller: FrontendBundle:General:historia }

escuchanos:
    pattern:  /escuchanos
    defaults: { _controller: FrontendBundle:General:escuchanos }

repertorio:
    pattern:  /repertorio
    defaults: { _controller: FrontendBundle:General:repertorio }

docsInteres:
    pattern:  /documentos-interes
    defaults: { _controller: FrontendBundle:General:documentos }

galeria:
    pattern:  /galeria
    defaults: { _controller: FrontendBundle:General:galeria }

contacto:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:General:contacto }
    requirements:
        _method:  GET
    
contacto_submit:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:General:contacto }
    requirements:
        _method:  POST