app:
    resource: "@AppBundle/Controller"
    type:     annotation

# Ruta dinámica que apuntará al director en activo
direccion:
    path:  /miembros/direccion
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: ficha_hilario_extremiana }
    methods:  [GET]

common_admin:
    resource: "@AppBundle/Resources/config/sonata_routing.yml"
    prefix:   /admin

admin_index:
    path:     /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: sonata_admin_dashboard, permanent: true }

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

private:
    resource: "@AppBundle/Resources/config/routing_private.yml"
    prefix:   /privado

rutas_migracion:
    resource: "@AppBundle/Resources/config/routing_migracion.yml"
    prefix:   /