frontend_general:
    resource: "@FrontendBundle/Resources/config/routing_general.yml"
    prefix:   /

frontend_miembro:
    resource: "@FrontendBundle/Resources/config/routing_miembros.yml"
    prefix:   /miembros

common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

common_admin:
    resource: "@CommonBundle/Resources/config/sonata_routing.yml"
    prefix:   /admin
    
admin_index:
    path:     /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: sonata_admin_dashboard, permanent: true }
    
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin
    