rutas_migracion:
    resource: "@FrontendBundle/Resources/config/routing_migracion.yml"
    prefix:   /

frontend_general:
    resource: "@FrontendBundle/Resources/config/routing_general.yml"
    prefix:   /

frontend_miembro:
    resource: "@FrontendBundle/Resources/config/routing_miembro.yml"
    prefix:   /miembros
    
frontend_concierto:
    resource: "@FrontendBundle/Resources/config/routing_concierto.yml"
    prefix:   /

common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

common_admin:
    resource: "@CommonBundle/Resources/config/sonata_routing.yml"
    prefix:   /admin
    
admin_index:
    path:     /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: sonata_admin_dashboard, permanent: true }
    
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

private:
        resource: "@PrivateBundle/Resources/config/routing.yml"
        prefix:   /privado
