security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Amcb\AppBundle\Entity\Usuario: plaintext

    role_hierarchy:
        ROLE_USUARIO:     [ROLE_BLOCKED]
        ROLE_ADMIN:       [ROLE_USUARIO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%admin_pass%", roles: [ 'ROLE_SUPER_ADMIN' ] }
        miembros:
            entity: { class: AppBundle:Usuario }
    firewalls:
        backend:
            pattern: ^/admin
            form_login: false
            provider: in_memory
            http_digest:
                realm:  "Area de administracion"
                key:    "%secret%"
            logout:
                path:   admin_logout
                target: homepage
                invalidate_session: false
        private:
            anonymous: ~
            pattern: ^/privado
            provider: miembros
            form_login:
                login_path: private_login
                check_path: private_login_check
                default_target_path: private_homepage
            logout:
                path:   private_logout
                target: homepage
                invalidate_session: false
        frontend:
            pattern: ^/*
            anonymous: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/privado/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/privado/, roles: ROLE_USUARIO }
