security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Amcb\CommonBundle\Entity\Miembro:
            algorithm: sha512
            encode_as_base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USUARIO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        backend:
            pattern: ^/admin
            form_login: false
            provider: in_memory
            http_digest:
                realm:  "Area de administracion"
                key:    "%secret%"
            logout:
                path:   admin_logout
                target: homepage
                invalidate_session: true
        frontend:
            pattern: ^/*
            anonymous: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }