private_homepage:
    pattern:  /
    defaults: { _controller: PrivateBundle:Default:index }

private_login:
    pattern:     /login
    defaults: { _controller: PrivateBundle:Default:login }

private_login_check:
    pattern: /login_check

private_logout:
    pattern:  /logout