parameters:
#    private.example.class: Amcb\PrivateBundle\Example

services:
#    private.example:
#        class: %private.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
