homepage:
    pattern:  /
    defaults: { _controller: AppBundle:General:index }

historia:
    pattern:  /historia
    defaults: { _controller: AppBundle:General:historia }

escuchanos:
    pattern:  /escuchanos
    defaults: { _controller: AppBundle:General:escuchanos }

repertorio:
    pattern:  /repertorio
    defaults: { _controller: AppBundle:General:repertorio }

docsInteres:
    pattern:  /documentos-interes
    defaults: { _controller: AppBundle:General:documentos }

galeria:
    pattern:  /galeria
    defaults: { _controller: AppBundle:General:galeria }

contacto:
    pattern:  /contacto
    defaults: { _controller: AppBundle:General:contacto }
    requirements:
        _method:  GET
    
contacto_submit:
    pattern:  /contacto
    defaults: { _controller: AppBundle:General:contacto }
    requirements:
        _method:  POST
