migracion_homepage:
    path:  /inicio.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: homepage, permanent: true }
    methods:  [GET]

migracion_historia:
    path:  /historia.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: historia, permanent: true }
    methods:  [GET]

migracion_contacto:
    path:  /contacto.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: contacto, permanent: true }
    methods:  [GET]

migracion_repertorio:
    path:  /repertorio.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: repertorio, permanent: true }
    methods:  [GET]

migracion_escuchanos:
    path:  /escuchanos.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: escuchanos, permanent: true }
    methods:  [GET]

migracion_galeria:
    path:  /galeria.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: galeria, permanent: true }
    methods:  [GET]

migracion_criticas:
    path:  /criticas.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: docsInteres, permanent: true }
    methods:  [GET]
    
migracion_homenaje_jesus_guridi:
    path:  /homenaje-jesus-guridi.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: docsInteres, permanent: true }
    methods:  [GET]


migracion_conciertos:
    path:  /eventos.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: conciertos, permanent: true }
    methods:  [GET]
    
migracion_archivo:
    path:  /archivo.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: archivo_conciertos, permanent: true }
    methods:  [GET]


migracion_miembros:
    path:  /miembros.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: miembros, permanent: true }
    methods:  [GET]

migracion_coro:
    path:  /coro.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: coro, permanent: true }
    methods:  [GET]

migracion_orquesta:
    path:  /orquesta.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: orquesta, permanent: true }
    methods:  [GET]

migracion_junta:
    path:  /junta.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: juntaDirectiva, permanent: true }
    methods:  [GET]

migracion_director:
    path:  /director.php
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: direccion, permanent: true }
    methods:  [GET]
