private_login:
    pattern:    /login
    defaults:   { _controller: AppBundle:Default:login }

private_login_check:
    pattern:    /login_check

private_logout:
    pattern:    /logout

private_fichero_listado:
    pattern:    /
    defaults:   { _controller: AppBundle:Fichero:index }

private_fichero_ver:
    pattern:    /fichero/ver/{id}
    defaults:   { _controller: AppBundle:Fichero:ver }

private_fichero_nuevo:
    pattern:    /fichero/subir
    defaults:   { _controller: AppBundle:Fichero:form }
    methods:  [GET]

private_fichero_editar:
    pattern:    /fichero/editar/{id}
    defaults:   { _controller: AppBundle:Fichero:form }
    methods:  [GET]

private_fichero_guardar:
    pattern:    /fichero/guardar/{id}
    defaults:   { _controller: AppBundle:Fichero:form, id: ~ }
    methods:  [POST]

private_fichero_eliminar:
    pattern:    /eliminar/{id}
    defaults:   { _controller: AppBundle:Fichero:eliminar }

# La última, para evitar una redirección cíclica hacia sí misma
private_homepage:
    pattern:    /
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: private_fichero_listado, permanent: true }
