parameters:

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    amcb.twig.extra_filter_extension:
        class: Amcb\AppBundle\Twig\Extension\ExtraFilterExtension
        tags:
            - { name: twig.extension }
    sonata.block.service.custom_buttons:
        class: Amcb\AppBundle\Block\CustomButtonsBlockService
        arguments: [ "sonata.block.service.custom_buttons", "@templating" ]
        tags:
            - { name: sonata.block }
    amcb.sonata.email_usuario:
        class: Amcb\AppBundle\EventListener\SonataEmailUsuarioListener
        arguments: [ "@mailer", "@templating" ]
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.persistence.post_persist, method: onNewUsuario }