parameters:

services:
    amcb.twig.controller_action_extension:
        class: Amcb\AppBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }
    amcb.twig.extra_filter_extension:
        class: Amcb\AppBundle\Twig\Extension\ExtraFilterExtension
        tags:
            - { name: twig.extension }
    amcb.twig.spanish_datetime_extension:
        class: Amcb\AppBundle\Twig\Extension\SpanishDateTimeExtension
        tags:
            - { name: twig.extension }
    sonata.block.service.custom_buttons:
        class: Amcb\AppBundle\Block\CustomButtonsBlockService
        arguments: [ "sonata.block.service.custom_buttons", "@templating" ]
        tags:
            - { name: sonata.block }
