homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Inicio:index }

historia:
    pattern:  /historia
    defaults: { _controller: FrontendBundle:Inicio:historia }

escuchanos:
    pattern:  /escuchanos
    defaults: { _controller: FrontendBundle:Inicio:escuchanos }

repertorio:
    pattern:  /repertorio
    defaults: { _controller: FrontendBundle:Inicio:repertorio }

docsInteres:
    pattern:  /documentos-interes
    defaults: { _controller: FrontendBundle:Inicio:documentos }

contacto:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:Inicio:contacto }