frontend_general:
    resource: "@FrontendBundle/Resources/config/routing_general.yml"
    prefix:   /

frontend_miembro:
    resource: "@FrontendBundle/Resources/config/routing_miembros.yml"
    prefix:   /miembros

common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /
