sancas_common:
    resource: "@SancasCommonBundle/Controller/"
    type:     annotation
    prefix:   /

frontend_inicio:
    resource: "@FrontendBundle/Resources/config/routing_inicio.yml"
    prefix:   /

frontend_miembro:
    resource: "@FrontendBundle/Resources/config/routing_miembros.yml"
    prefix:   /miembros
