parameters:

services:
    amcb.twig.amcb_extension:
        class: Amcb\CommonBundle\Twig\Extension\ControllerActionExtension
        arguments: ["@request="]
        tags:
            - { name: twig.extension }
