parameters:

services:
    amcb.twig.controller_action_extension:
        class: Amcb\CommonBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }